import { readFile } from "node:fs/promises";
import path from "node:path";

const repositoryRoot = path.resolve(import.meta.dirname, "..");

export const reportSchemaPath = path.join(
  repositoryRoot,
  "packages/contracts/schemas/structured-report.v1.schema.json",
);

export const generatedReportTypePath = path.join(
  repositoryRoot,
  "packages/contracts/src/generated/structured-report.v1.ts",
);

export const buildGeneratedReportTypes = async (): Promise<string> => {
  const rawSchema = await readFile(reportSchemaPath, "utf8");
  const schema: unknown = JSON.parse(rawSchema);

  return [
    "// Generated by scripts/generate-report-types.ts. Do not edit manually.",
    'import type { FromSchema } from "json-schema-to-ts";',
    "",
    `export const structuredReportV1Schema = ${JSON.stringify(schema, null, 2)} as const;`,
    "",
    "export type StructuredReportV1 = FromSchema<",
    "  typeof structuredReportV1Schema",
    ">;",
    "",
  ].join("\n");
};
